### ISSUE TITLE
Kiritilgan qiymatni tekshirishda xatolik )

### ISSUE THREAD

**Issue by udilbar** [Muhammadboburshoh/go-first#1]
![Screenshot_9](https://user-images.githubusercontent.com/68459485/98666083-538c2400-236e-11eb-9b6c-301f24183a83.png)
Inputga string turidagi ma'lumotni kiritganimizda, alert xabarimizni shunga moslab o'zgatirib qo'yganimiz yaxshi ) Masalan, string turidagi ma'lumot kiritilganida, quyidagicha alert xabar chiqsin:
"Masofani raqamda kiriting" yoki "Ma'sofani so'zda kiritmang" kabi )

**Comment by Muhammadboburshoh** [comment]
Rahmat)
